upload script logs to storage account
Azure/ArcOnAVSInternal pull request #3
Opened 2022-11-23 19:38 UTC by abhi580

upload script logs to storage account

2022-11-24 04:28 UTC, msfttusharjuneja commented on src/appliance-onboarding-script/appliance_setup/avs/avsarconboarder/constants/Constant.py
> +VALID_LOCATIONS = "westeurope,eastus,australiaeast,canadacentral,uksouth,southeastasia"
Remove this change if not required

2022-11-24 04:32 UTC, msfttusharjuneja commented on src/appliance-onboarding-script/appliance_setup/avs/avsarconboarder/logger/_collect_logs.py
> +        os.makedirs(logs_folder)
Should we leverage the existing logs folder for this? Given we don't anticipate multiple runs on the same VM?

2022-11-24 04:48 UTC, msfttusharjuneja commented on src/appliance-onboarding-script/appliance_setup/avs/avsarconboarder/logger/_collect_logs.py
> +            shutil.copy('output.txt', self.logs_folder)
Does it make more sense to call it console_output.txt?

2022-11-24 04:53 UTC, msfttusharjuneja commented on src/appliance-onboarding-script/appliance_setup/avs/avsarconboarder/logger/_collect_logs.py
> +            logging.info("Insufficient logs captured")
Should this be an info or an error? Should we raise it further?

2022-11-24 04:53 UTC, msfttusharjuneja commented on src/appliance-onboarding-script/appliance_setup/avs/avsarconboarder/logger/_collect_logs.py
> +            logging.info("Insufficient logs captured")
We should atleast print the exception's message along for more info on what went wrong

2022-11-24 04:56 UTC, msfttusharjuneja commented on src/appliance-onboarding-script/appliance_setup/avs/avsarconboarder/logger/_collect_logs.py
> +            logging.info("failed to fetch arc appliance logs")
Should this be an info or an error? Should we raise it further?

We should atleast print the error message along for more info on what went wrong

2022-11-24 05:50 UTC, abhi580 commented on src/appliance-onboarding-script/appliance_setup/avs/avsarconboarder/logger/_collect_logs.py
> +            shutil.copy('output.txt', self.logs_folder)
In template, the output is redirected to output.txt, we should make a change over there too. LMK if it should be done?

2022-11-24 05:59 UTC, abhi580 commented on src/appliance-onboarding-script/appliance_setup/avs/avsarconboarder/constants/Constant.py
> +VALID_LOCATIONS = "westeurope,eastus,australiaeast,canadacentral,uksouth,southeastasia"
sure

2022-11-24 06:27 UTC, abhi580 commented on src/appliance-onboarding-script/appliance_setup/avs/avsarconboarder/logger/_collect_logs.py
> +        os.makedirs(logs_folder)
We are anyways copying the other files to this folder(duplicating) and we can just have same timestamp in jumpbox and in storage account. we might need different folder names in storage account, if the customer tries to onboard twice and faces a failure 2 times and it would be easy to investigate. LMK otherwise.

2022-11-24 06:35 UTC, msfttusharjuneja commented on src/appliance-onboarding-script/appliance_setup/avs/avsarconboarder/logger/_collect_logs.py
> +        except:
What are the scenarios in which exception occurs?
Have we considered all the below scenarios:
1) Appliance VM doesn't exist.
2) Appliance VM did not get an IP.
3) Appliance VM is present but logs weren't created (due to some error)

2022-11-24 07:22 UTC, msfttusharjuneja commented on src/appliance-onboarding-script/appliance_setup/avs/avsarconboarder/logger/_upload_logs.py
> +            raise AzCommandError('failed to create container')
Print err received from az. Consider this for all the other places as well

2022-11-24 07:46 UTC, msfttusharjuneja commented on src/appliance-onboarding-script/appliance_setup/avs/avsarconboarder/logger/_collect_logs.py
> +        os.makedirs(logs_folder)
Makes sense. Does it make sense to have this timestamp aligned with the timestamp we use for Run commands in automated onboarding though?

2022-11-24 07:46 UTC, msfttusharjuneja commented on src/appliance-onboarding-script/appliance_setup/avs/avsarconboarder/logger/_collect_logs.py
> +            shutil.copy('output.txt', self.logs_folder)
Sure, we can do that.

2022-11-24 07:50 UTC, abhi580 commented on src/appliance-onboarding-script/appliance_setup/avs/avsarconboarder/logger/_collect_logs.py
> +        os.makedirs(logs_folder)
I should get the timestamp from RunCommand. will make the changes at both the places.

2022-11-24 07:55 UTC, abhi580 commented on src/appliance-onboarding-script/appliance_setup/avs/avsarconboarder/logger/_collect_logs.py
> +            shutil.copy('output.txt', self.logs_folder)
done

2022-11-24 07:57 UTC, abhi580 commented on src/appliance-onboarding-script/appliance_setup/avs/avsarconboarder/logger/_upload_logs.py
> +            raise AzCommandError('failed to create container')
def az_cli (*args) -> This function prints it anyways. 
err value returned is a 0 or 1.

2022-11-24 09:16 UTC, abhi580 commented on src/appliance-onboarding-script/appliance_setup/avs/avsarconboarder/logger/_collect_logs.py
> +            logging.info("Insufficient logs captured")
will log it as error, raising it will exit the code and will not collect the arc-appliance logs that is called later.

2022-11-24 09:41 UTC, abhi580 commented on src/appliance-onboarding-script/appliance_setup/avs/avsarconboarder/logger/_collect_logs.py
> +            logging.info("failed to fetch arc appliance logs")
error is already printed in azcli() function. removing logging here as it is already captured in azcli().  Not raising it because it will exit and will not upload files to container.

2022-11-24 09:47 UTC, abhi580 commented on src/appliance-onboarding-script/appliance_setup/avs/avsarconboarder/logger/_collect_logs.py
> +        except:
`res, err = az_cli('arcappliance', 'logs', 'vmware', 
                        '--ip', f'"{arc_appliance_ip}"',
                        '--address', f'"{vcenter_ip}"',
                        '--username',f'"{vcenter_username}"',
                        '--password="{}"'.format(safe_escape_characters(vcenter_password)))
        `
In all these scenarios, above azcli() would log it in error. We will not find folder and will also log that folder is not found

2022-11-24 10:01 UTC, msfttusharjuneja commented on src/appliance-onboarding-script/appliance_setup/avs/avsarconboarder/logger/_collect_logs.py
> +            logging.info("Insufficient logs captured")
Unless we handle the exception there. This is also fine if you think this is better.

2022-11-24 10:07 UTC, msfttusharjuneja commented on src/appliance-onboarding-script/appliance_setup/avs/avsarconboarder/logger/_upload_logs.py
> +            raise AzCommandError('failed to get container details')
>AzCommandError [](http://example.com/codeflow?start=18&length=14)

If we are not able to fetch the container, do we really want to fail the uploading of the rest of the logs?

2022-11-26 08:10 UTC, msfttusharjuneja commented on src/appliance-onboarding-script/appliance_setup/avs/avsarconboarder/logger/_collect_logs.py
> +        os.makedirs(logs_folder)
On second thought, I think it might be an overhead to pass along the timestamp, hence we can skip it for now.

2022-11-26 08:13 UTC, msfttusharjuneja commented on src/appliance-onboarding-script/appliance_setup/avs/avsarconboarder/logger/_upload_logs.py
> +            raise AzCommandError('failed to get container details')
This is NIT, since this az command will fail if there is a fundamental issue (az cli issue/connectivity issue) and eventually it might fail at a later point as well. 
Also it is fine to fail at this point as well.

2022-11-26 08:30 UTC, msfttusharjuneja requested changes
As discussed, let's wait and figure out where should we add the storage account blob contributor access and the go ahead with the changes.

2022-11-26 10:52 UTC, msfttusharjuneja commented on src/appliance-onboarding-script/appliance_setup/run.py
> +        except Exception as e:
Do we not want to raise any exception in case the logs weren't uploaded successfully?

2022-12-07 10:13 UTC, abhi580 commented on src/appliance-onboarding-script/appliance_setup/avs/avsarconboarder/logger/_collect_logs.py
> +        except:
it does not cause any exception, it is just printed in azcli().

2022-12-07 10:16 UTC, abhi580 commented on src/appliance-onboarding-script/appliance_setup/run.py
> +        except Exception as e:
Since this is not fatal to onboard of arc, I haven't raised exception and exiting the code. logging it as error for now. LMK if you have any thoughts.

2022-12-12 05:07 UTC, msfttusharjuneja commented on src/appliance-onboarding-script/run.ps1
> +    if($OperationExitCode -ne 0)
>-ne 0 [](http://example.com/codeflow?start=26&length=5)

Should we offboard for all non zero exit codes or not?

2022-12-12 05:15 UTC, msfttusharjuneja commented on src/appliance-onboarding-script/appliance_setup/pkgs/_exceptions.py
>  class ArmFeatureNotRegistered(Exception): pass
Is change in this file expected? If not, can we revert it?

2022-12-12 05:17 UTC, msfttusharjuneja commented on src/appliance-onboarding-script/appliance_setup/avs/avsarconboarder/logger/_upload_logs.py
> +        if err:
> if err: [](http://example.com/codeflow?start=7&length=8)

Is this a fatal exception for Upload logs? If yes, should we raise an exception here?

2022-12-13 09:31 UTC, abhi580 commented on src/appliance-onboarding-script/run.ps1
> +    if($OperationExitCode -ne 0)
From discussions, we have concluded that we will offboard for all failures atleast for private-preview.

2022-12-13 09:58 UTC, msfttusharjuneja commented on src/appliance-onboarding-script/appliance_setup/avs/avsarconboarder/logger/_upload_logs.py
> +        if err:
We should always fail at the point of failure and not wait for the failure to propagate and fail at another point. This is because we get the most accurate error at this point.
Do verify the behavior if there is of the az cli in case the role assignment is pre-existing (This is in case of retries etc)

2022-12-15 05:20 UTC, abhi580 commented on src/appliance-onboarding-script/appliance_setup/avs/avsarconboarder/logger/_upload_logs.py
> +        if err:
We do not get any error on retries(pre-existing role assignments). Logging it as error right now.

2022-12-15 08:20 UTC, msfttusharjuneja commented on src/appliance-onboarding-script/appliance_setup/avs/avsarconboarder/logger/_upload_logs.py
> +        if err:
in that case should we raise an exception here?

2022-12-15 09:55 UTC, abhi580 commented on src/appliance-onboarding-script/appliance_setup/avs/avsarconboarder/logger/_upload_logs.py
> +        if err:
yes let's keep an exception here.

2022-12-16 04:49 UTC, msfttusharjuneja approved these changes

2022-12-16 04:58 UTC, merged